### ISSUE TITLE
IE8 users do not get asked permission

### ISSUE THREAD

**Issue by jmonkfish** [estebanav/javascript-mobile-desktop-geolocation#2]
Love this script, but it doesn't appear to be asking permission for IE users (IE 6, 7, 8)

http://dev.w3.org/geo/api/spec-source.html#security - Section 4
"A conforming implementation of this specification must provide a mechanism that protects the user's privacy and this mechanism should ensure that no location information is made available through this API without the user's express permission."

**Comment by estebanav** [comment]
Thanks jmonkfish!

If you are able to solve this issue, please fork the project and ask for a Pull Request. If not, I´ll take care in the next days as I have just came back from vacations :)

Thanks again,

**Comment by estebanav** [comment]
Solved :)

**Comment by jonathantneal** [comment]
Thanks!
