### ISSUE TITLE
Usage Limits?

### ISSUE THREAD

**Issue by efkan** [estebanav/javascript-mobile-desktop-geolocation#4]
Hi,

Is there any limit to use? 
For instance Google Maps Javascript API V3's limit daily 2500 request.

And this library use more than one different services. Doesn't it?

Anyway it's a perfect work! Thanks..

**Comment by estebanav** [comment]
Hi efkan,

The external library (http://freegeoip.net/) is limited to 10,000 queries per hour. As the library is licensed as OpenSource you can create your own Geolocatisation service, please see Library's documentation to do this.

Thanks!

E.
